package datafusion-udf-wasm:udf@0.1.0;

interface types {
    resource scalar-udf {
        name: func() -> string;
    }

    scalar-udfs: func() -> list<scalar-udf>;
}

world datafusion {
    export types;
}
