PYTHON_VERSION_MAJOR := "3"
PYTHON_VERSION_MINOR := "14"
PYTHON_VERSION_MICRO := "0"

PYTHON_VERSION_FULL := PYTHON_VERSION_MAJOR + "." + PYTHON_VERSION_MINOR + "." + PYTHON_VERSION_MICRO

DOWNLOADS_DIR := source_directory() / "downloads"

export PYO3_CROSS_PYTHON_VERSION := PYTHON_VERSION_MAJOR + "." + PYTHON_VERSION_MINOR
export PYO3_CROSS_LIB_DIR := DOWNLOADS_DIR / "python-sdk"

PYTHON_TMP_VENV := DOWNLOADS_DIR / "venv"
PYTHON_SITE_PACKAGES := PYO3_CROSS_LIB_DIR / "lib" / "python" + PYO3_CROSS_PYTHON_VERSION / "site-packages"

export WASI_SDK_LINK_PATH := DOWNLOADS_DIR / "wasi-sysroot" / "lib" / "wasm32-wasip2"


# Note: Downloads are now handled by build.rs during the cargo build process
[private]
python-site-packages:
    #!/usr/bin/env bash
    set -euo pipefail

    echo ::group::guests::python::python-site-packages
    set -x

    # skip if already downloaded
    if [ -d python-sdk ]; then
        echo "site-packages already set up"
        set +x
        echo ::endgroup::
        exit 0
    fi

    python3 -m venv "{{PYTHON_TMP_VENV}}"

    # Notes:
    # - "only binary" means "only wheels, no sdist", i.e. we don't need to run any Python lib build code
    # - "implementation=py" ensures that we use the most neutral wheel possible, i.e. not actual binary code
    "{{PYTHON_TMP_VENV}}"/bin/pip install \
        --disable-pip-version-check \
        --no-deps \
        --ignore-installed \
        --implementation=py \
        --isolated \
        --only-binary=:all: \
        --python-version={{PYTHON_VERSION_FULL}} \
        --requirement=requirements.txt \
        --target="{{PYTHON_SITE_PACKAGES}}"

    set +x
    echo ::endgroup::

[private]
build-lib profile: python-site-packages
    @echo ::group::guests::python::build-lib {{profile}}
    cargo build --target=wasm32-wasip2 --profile={{replace(profile, "debug", "dev")}}
    @echo ::endgroup::

# top-level entry point
[private]
do profile: (build-lib profile)

# create dev/debug build
build-debug: (do "debug")

# create release build
build-release: (do "release")

# checks build
check-build: build-debug

# clean build artifacts
clean:
    @echo ::group::guests::python::clean
    cargo clean
    @echo ::endgroup::
