[private]
build-add-one profile:
    @echo ::group::guests::rust::build-add-one {{profile}}
    cargo +nightly build --target=wasm32-wasip2 --example=add_one --profile={{replace(profile, "debug", "dev")}}
    @echo ::endgroup::

# build `add-one` example in debug mode
build-add-one-debug: (build-add-one "debug")

# build `add-one` example in release mode
build-add-one-release: (build-add-one "release")

# checks build
check-build: build-add-one-debug
