---
name: CI

# yamllint disable-line rule:truthy
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 1

      - name: Fetch main branch
        run: git fetch --depth=1 origin main

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Install `uv`
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          version-file: "python-tooling/pyproject.toml"

      - name: Install `python`
        shell: bash
        run: |
          uv --directory=python-tooling python install --default

          path_exe="$(uv --directory=python-tooling python find)"
          path_bin="$(dirname "$path_exe")"
          echo "PYO3_CROSS_LIB_DIR=${path_bin}/../lib" >> "$GITHUB_ENV"
          echo "LD_LIBRARY_PATH=${path_bin}/../lib" >> "$GITHUB_ENV"

      - name: Install `cargo-deny` & `just` & `tombi` & 'typos' & 'wasm-tools'
        uses: taiki-e/install-action@055f5df8c3f65ea01cd41e9dc855becd88953486  # v2
        with:
          tool: cargo-deny,just,tombi,typos,wasm-tools
          # only allow tools that got pinned via `install-action` to prevent supply chain attacks and surprise-upgrades
          fallback: none

      - name: Install Rust toolchain
        run: rustup toolchain install

      - name: Rust Cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4  # v2.9.1

      - name: just check
        run: just check
        env:
          # Disable incremental compilation to avoid overhead.
          CARGO_INCREMENTAL: "0"
          # Disable full debug symbol generation to speed up CI build
          # "1" means line tables only, which is useful for panic tracebacks.
          CARGO_PROFILE_DEV_DEBUG: "1"

      - name: Check Cargo.lock
        shell: bash
        run: |
          if ! git diff --exit-code -- Cargo.lock; then
              echo "::error::Cargo.lock changed, please commit your local changes!"
              exit 1
          else
              echo "Good. Cargo.lock is up to date"
          fi

      - name: upload docs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: docs
          path: target/doc
          if-no-files-found: error
